name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        GOPATH: ${{ github.workspace }}/go
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13'
    - name: Install promu
      run: make promu
    - name: Build
      run: make build
    - name: Publish to Registry
      uses: HurricanKai/Publish-Docker-Github-Action@master
      if: contains(github.ref, 'refs/tags/v')
      with:
        name: tarvip/kafka-exporter
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        cache: true
        tagging: true
